apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: REGISTRY/frontend
    newName: AZURE_ACR.azurecr.io/frontend
  - name: REGISTRY/api
    newName: AZURE_ACR.azurecr.io/api
patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: HOSTNAME
    target:
      kind: Ingress
      name: ha-ingress
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass
        value: azure-kv-api
    target:
      kind: Deployment
      name: api
